# coding: utf-8

"""
    CCCS

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.comments_api import CommentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommentsApi(unittest.TestCase):
    """CommentsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.comments_api.CommentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_comment(self):
        """Test case for create_comment

        Post a comment  # noqa: E501
        """
        pass

    def test_delete_comment(self):
        """Test case for delete_comment

        Remove a Comment  # noqa: E501
        """
        pass

    def test_get_comment(self):
        """Test case for get_comment

        Get a single comment  # noqa: E501
        """
        pass

    def test_get_comments(self):
        """Test case for get_comments

        Get a single comment  # noqa: E501
        """
        pass

    def test_update_comment(self):
        """Test case for update_comment

        Modify/Create a Comment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
