# coding: utf-8

"""
    CCCS

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_api import UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        Registration end point for a user account  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete user (only allowed by the user themselves)  # noqa: E501
        """
        pass

    def test_generate(self):
        """Test case for generate

        Post auth for token response  # noqa: E501
        """
        pass

    def test_get_subs(self):
        """Test case for get_subs

        Get all submissions for a user (or those matching an ID)  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get all users (or those matching an ID)  # noqa: E501
        """
        pass

    def test_get_users(self):
        """Test case for get_users

        """
        pass

    def test_login(self):
        """Test case for login

        Allow a user to login  # noqa: E501
        """
        pass

    def test_reset(self):
        """Test case for reset

        Reset user password  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update user details (change password, add details etc)  # noqa: E501
        """
        pass

    def test_validate(self):
        """Test case for validate

        OAuth2 token info  # noqa: E501
        """
        pass

    def test_verify_reset(self):
        """Test case for verify_reset

        Verify password reset token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
