# coding: utf-8

"""
    CCCS

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.projects_api import ProjectsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.projects_api.ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_project(self):
        """Test case for create_project

        Post a project  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Remove a project  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Get a single project  # noqa: E501
        """
        pass

    def test_get_project_count(self):
        """Test case for get_project_count

        Get row count of query  # noqa: E501
        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        Get all projects  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Modify/Create a project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
