# coding: utf-8

"""
    CCCS

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.activities_api import ActivitiesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestActivitiesApi(unittest.TestCase):
    """ActivitiesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.activities_api.ActivitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_activity(self):
        """Test case for create_activity

        Post a activity  # noqa: E501
        """
        pass

    def test_delete_activity(self):
        """Test case for delete_activity

        Remove an Activity  # noqa: E501
        """
        pass

    def test_get_activities(self):
        """Test case for get_activities

        Get all Activities  # noqa: E501
        """
        pass

    def test_get_activity(self):
        """Test case for get_activity

        Get a single activity  # noqa: E501
        """
        pass

    def test_get_activity_count(self):
        """Test case for get_activity_count

        Get row count of query  # noqa: E501
        """
        pass

    def test_update_activity(self):
        """Test case for update_activity

        Modify/Create a Activity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
