# coding: utf-8

"""
    CCCS

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.submissions_api import SubmissionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubmissionsApi(unittest.TestCase):
    """SubmissionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.submissions_api.SubmissionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_submission(self):
        """Test case for create_submission

        Post a submission  # noqa: E501
        """
        pass

    def test_delete_submission(self):
        """Test case for delete_submission

        Remove a submission  # noqa: E501
        """
        pass

    def test_get_submission(self):
        """Test case for get_submission

        Get a single submission  # noqa: E501
        """
        pass

    def test_get_submission_count(self):
        """Test case for get_submission_count

        Get row count of query  # noqa: E501
        """
        pass

    def test_get_submissions(self):
        """Test case for get_submissions

        Get a single submission  # noqa: E501
        """
        pass

    def test_update_submission(self):
        """Test case for update_submission

        Modify/Create a submission  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
